language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t pgavigan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pgavigan/docker-react npm run test